### ISSUE TITLE
How to use Peek?

### ISSUE THREAD

**Issue by paulcanning** [Flipboard/bottomsheet#63]
I cannot find any documentation on how to use the peek feature?

I'd like my sheet to peek, then expand when tapped or dragged up.

**Comment by hzsweers** [comment]
That's normal behavior. You can control peek, expand, and dismiss via the appropriate helper methods:


`expandSheet()`

`peekSheet()`

`dismissSheet()`

**Comment by paulcanning** [comment]
I tried peekSheet()  but it crashed my app. Do I call it alone or with showSheetWithView?

**Comment by hzsweers** [comment]
showWithSheetView will automatically start it in peek state. You should
only be calling peekSheet() to collapse it from its expanded state.

**Comment by paulcanning** [comment]
That's not the case for me. But like I said, I have a height set. Should I remove it?

**Comment by hzsweers** [comment]
You can control a custom peek size with `setPeekSheetTranslation`

Note that if you don't set MATCH_PARENT, it will try to wrap the content. If the wrapped content height is smaller than the screen, then it will just wrap the whole content.

Your interpretation is correct, that is what it means. Relative to EXPANDED, it is a collapse.

**Comment by paulcanning** [comment]
When I set the height with a dp value, it didn't wrap to the content. Should I use wrap_content for the height? 

LinearLayouts (which I'm using for my custom sheet view) need a height parameter.

**Comment by hzsweers** [comment]
It's really hard to help without seeing at least a sample of the code or layout you're trying to execute.

Can you paste a snippet of how you're showing your sheet and what the layout parameters are?

wrap_content will do exactly what it suggests. If its height is smaller than the height of the screen, then it will supercede any custom peek height you set. If you set the height to match_parent, then the custom peek height comes into play since you can actually have both expanded and peeked states.

**Comment by paulcanning** [comment]
MainActivity.java

in OnCreate:

    bottomSheet = (BottomSheetLayout) findViewById(R.id.bottomsheet);

When tapping a button:

    View myView = LayoutInflater.from(getApplicationContext()).inflate(R.layout.my_sheet_layout, bottomSheet, false);

    TextView title = (TextView) myView.findViewById(R.id.sheetTitle);
    TextView note= (TextView) myView.findViewById(R.id.sheetNote);
    note.setText('Note');

    bottomSheet.showWithSheetView(myView);

my_sheet_layout.xml

    <LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_height="match_parent"
    android:layout_width="match_parent"
    android:background="#ffffff"
    android:orientation="vertical" >

    <View
        android:id="@+id/moteBar"
        android:layout_height="16dp"
        android:layout_width="match_parent"
        android:background="#000"
        android:layout_marginBottom="8dp"
        />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Title"
        android:textSize="16sp"
        android:id="@+id/sheetTitle"
        android:textColor="#000"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp" />

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Note"
        android:textSize="14sp"
        android:id="@+id/sheetNote"
        android:textColor="#000"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp" />

    </LinearLayout>

Attached is a screenshot showing the sheet. It has peeked higher then the content. I want the peek height to be enough to show the title and note.

Then later if I add extra content, I'd like the peek to stay the same (title and note wrapped), then let me expand to see the extra content.

![screenshot_2015-09-16-12-37-48](https://cloud.githubusercontent.com/assets/1275739/9903746/b22b23b4-5c70-11e5-930c-26b5755d4844.png)

**Comment by paulcanning** [comment]
Why was this closed? I never got an answer :/

I'm still struggling with peekSheet() and how to set the size of the initial, small sheet view (before it is expanded) as the documentation is lacking this info

**Comment by hzsweers** [comment]
I thought it was resolved, and you had several comments after it was closed so I assumed you were OK with it?

I missed the bit about adding content later, that's an important detail. I'm honestly not sure how it behaves in that situation, I imagine if it's wrapping content, it makes sense for it to continue wrapping content

**Comment by hzsweers** [comment]
I already explained farther up how to set a custom peek height though, did you see that?

**Comment by paulcanning** [comment]
I added comments to show how I was implementing bottomSheet and tried to explain what I want. 

To recap:

peekSheet() is a total mystery. The name,to me, implies I can call it (sheet.peekSheet()) and it would show a bit (a peek) of the sheet. 

According to you, that's incorrect. Fair enough. But I'm still not sure what it should do if you call the method. 

Anyway,  in my sheet, I have a title, some text and then a photo. 

I want to show the sheet with just the title and text (single line text), so the user can see most of the main view, with a sheet "preview" at the bottom. 

Then, on tapping or swiping up, I want the sheet to expand so the title, text and the photo are visible, taking up the entire screen. 

Right now, I can show the small sheet "preview" but have literally no idea what so ever on how to set the height so you can only view the title and text.

**Comment by hzsweers** [comment]
> peekSheet() is a total mystery. The name,to me, implies I can call it (sheet.peekSheet()) and it would show a bit (a peek) of the sheet.

That is what is does, that is also the behavior used in the design support library implementation.

> According to you, that's incorrect. 

No, I didn't say that. I said that if you're using `wrap_content`, then it's just going to show the wrapped size of the sheet unless it's equal to or larger than the display

> I want to show the sheet with just the title and text (single line text), so the user can see most of the main view, with a sheet "preview" at the bottom.

Then you need to set the peek height to the measured height of those two components, or use the design support library's bottom sheet.

What you're describing now is not really what you were describing before, and it's also not something this library readily supports. I would suggest using the design support library or [SlidingUpPanelLayout](https://github.com/umano/AndroidSlidingUpPanel).

**Comment by paulcanning** [comment]
I tried using peekSheet() instead of showWithSheetView() and I got an Null
Pointer Exception.

If I need to set the peek height, how? I can't see any information on how
to do this.

**Comment by hzsweers** [comment]
For the last time: `setPeekSheetTranslation` sets the peek height. I've said this multiple times. Pass in the height in pixels that you want.

You're going to get a NPE for trying to call peekSheet before showWithSheetView() because it has nothing to show until after the latter call.

So to be clear:
```java
bottomSheetLayout.setPeekSheetTranslation(yourPreferredHeight);
bottomSheetLayout.showWithSheetView(yourSheetView);
```

If you have your layout params on `yourSheetView` set to wrap content however, that will take precedent over any possible states. If you want both `peek` and `expanded` behavior, you'll need to match parent for now.

**Comment by paulcanning** [comment]
How do I use dp as the height units? Using pixels is pretty useless tbh :/

**Comment by hzsweers** [comment]
Setting dimensions on Android programmatically is almost always in pixels. There are plenty of ways you could do this:

- manually measure your header vies height and then retrieve it via getMeasuredHeight
- if you have the height in resources, you can retrieve it getDimensionPixelSize
- if you want to convert from DPs to pixels on the fly, there are tons of stackoverflow answers with the quick functions you need to do the math. Just search `dp2px`
